// Walks ../bootstrap-project, collects every .md file, and writes data.js.
// Run with:  node build.mjs
// Re-run whenever the skill's markdown files change.

import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { dirname } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..', 'bootstrap-project');

function walk(dir, acc = []) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const st = statSync(full);
    if (st.isDirectory()) walk(full, acc);
    else if (entry.endsWith('.md')) acc.push(full);
  }
  return acc;
}

const files = walk(root)
  .map((abs) => ({
    path: relative(root, abs).split(sep).join('/'),
    content: readFileSync(abs, 'utf8'),
  }))
  .sort((a, b) => a.path.localeCompare(b.path));

const payload = {
  skillName: 'bootstrap-project',
  generatedAt: new Date().toISOString(),
  files,
};

writeFileSync(
  join(here, 'data.js'),
  `// Auto-generated by build.mjs — do not edit by hand.\nwindow.SKILL_DATA = ${JSON.stringify(payload, null, 2)};\n`
);

console.log(`Wrote data.js with ${files.length} markdown files.`);
